import Head from 'next/head'
import { ReactElement } from 'react'
import DashboardLayout from '../layout/dashboard'
import DashboardContainer from '../container/dashboard'
import { Button } from 'antd'
import ProductContainer from '../container/products'

export default function ProductsPage() {
  return (
    <>
      <Head>
        <title>Sản phẩm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductContainer />
    </>
  )
}

ProductsPage.getLayout = (page: ReactElement) => {
  return <DashboardLayout>{page}</DashboardLayout>
}
